version: '3.8'

services:
  mock-simulation:
    image: wiremock/wiremock:3.3.1
    container_name: fidc-mock-simulation
    ports:
      - "8081:8080"
    volumes:
      - ./mock/simulation:/home/wiremock
    command: --global-response-templating --verbose
    networks:
      - fidc-network

volumes: {}

networks:
  fidc-network:
    external: true
    name: fidc-network