spring:
  application:
    name: fidc-gateway-test
  
  # Desabilitar Redis para testes
  data:
    redis:
      enabled: false

server:
  port: 0

management:
  endpoints:
    web:
      exposure:
        include: health

logging:
  level:
    com.banco.fidc.gateway: DEBUG