spring:
  application:
    name: fidc-gateway

  profiles:
    active: local
  
  cloud:
    gateway:
      routes:
        - id: health-check
          uri: http://localhost:8080
          predicates:
            - Path=/actuator/health
            
        - id: simulation-create
          uri: http://localhost:8081
          predicates:
            - Path=/api/simulation/create/**
          filters:
            - name: SessionValidationFilter
              args:
                requiredPermissions: 
                  - CREATE_SIMULATION
                  
        - id: simulation-view
          uri: http://localhost:8081
          predicates:
            - Path=/api/simulation/view/**
          filters:
            - name: SessionValidationFilter
              args:
                requiredPermissions: 
                  - VIEW_PROFILE

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics
  endpoint:
    health:
      show-details: when-authorized

resilience4j:
  circuitbreaker:
    configs:
      default:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        sliding-window-size: 10