spring:
  application:
    name: fidc-gateway

  profiles:
    active: local
  
  cloud:
    gateway:
      routes:
        - id: health-check
          uri: http://localhost:8080
          predicates:
            - Path=/actuator/health
            
        # Rota para Simulation Service (Mock)
        - id: simulation-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/simulation/**
          filters:
            - name: SessionValidationFilter
              args:
                requiredPermissions: []
                
        # Rota para Contract Service (Mock) 
        - id: contract-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/contract/**
          filters:
            - name: SessionValidationFilter
              args:
                requiredPermissions: []
                
        # Rota para Profile Service (Mock)
        - id: profile-service  
          uri: http://localhost:8083
          predicates:
            - Path=/api/profile/**
          filters:
            - name: SessionValidationFilter
              args:
                requiredPermissions: []
                
        # Rota para Query Service (Mock)
        - id: query-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/query/**
          filters:
            - name: SessionValidationFilter
              args:
                requiredPermissions: []

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics
  endpoint:
    health:
      show-details: when-authorized

resilience4j:
  circuitbreaker:
    configs:
      default:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        sliding-window-size: 10