spring:
  redis:
    host: localhost
    port: 6379
    password: ""
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 10
        max-idle: 5
        min-idle: 2

microservices:
  base-url: http://localhost

management:
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.banco.fidc.gateway: DEBUG
    io.lettuce.core: DEBUG
    reactor.netty: DEBUG

